kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands:
      - dotnet sonarscanner begin 
        /k:"easv-devops_Julian-Old-Project_AY2-c-wYEVvRW2O60EDs" 
        /d:sonar.host.url="http://sonar.setgo.dk:9000"  
        /d:sonar.token="sqp_f21da017589947eb7bebf0a03634071e298299d4"
        /d:sonar.cs.vscoveragexml.reportPaths=coverage.xml
        /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental 
      - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="sqp_f21da017589947eb7bebf0a03634071e298299d4"
